server:
  port: 5001

spring:
  application:
    name: restAPI_java
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  mail:
    host: ${SMTP_ADDRESS}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    root: INFO
    com.example.restapi_java: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.mail: DEBUG
  file:
    name: logs/app.log

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: ${JWT_SECRET}

admin:
  default:
    password: ${ADMIN_PASSWORD}

app:
  rabbitmq:
    exchange: user-exchange

    user-notification-queue:
      name: user-notification-queue
      routing-key: user.notification.queue

